Activity 1

In [ ]:
def maximum(num1, num2, num3):
    result = max(num1, num2, num3)
    return result
n1=int(input('Enter a number '))
n2=int(input('Enter a number '))
n3=int(input('Enter a number '))
m = maximum(n1, n2, n3)
print("Maximum number is:", m)

Enter a number 3
Enter a number 6
Enter a number 1
Maximum number is: 6


Activity 2

In [ ]:
def circle_area (radius):
    pi = 3.14159
    area = pi * radius ** 2
    return area
n1=int(input('Enter a number '))
a = circle_area(n1)
print("Area is:", a)

Enter a number 4
Area is: 50.26544


Activity 3

In [ ]:
prime=int(input('Enter a number '))
def prm(p):
 for i in range(2,p):
   if(p%i==0):
    return False
    break
 else:
  return True
prm(prime)

Enter a number 6


False

Activity 4

In [ ]:
strng=input('Enter a word ')
s=len(strng)
def pal(n):
  if(n[s::-1]==n):
    return True
  else:
    return False
pal(strng)

Enter a word amma


True

Activity 5

In [ ]:
s=int(input('What is the size of list '))
def add(s):
 d=[]
 su=0
 for i in range(s):
  num=int(input('Number= '))
  d.append(num)
  su=su+num
 print(d)
 return print("sum= ",su)
add(s)

What is the size of list 4
Number= 1
Number= 9
Number= 7
Number= 3
[1, 9, 7, 3]
sum=  20


Activity 6

In [ ]:
s=int(input('What is the size of list '))
def avrg(s):
 d=[]
 su=0
 for i in range(s):
  num=int(input('Number= '))
  d.append(num)
  su=su+num
 avg= su/s
 print(d)
 return print("avg= ",avg)
avrg(s)

What is the size of list 4
Number= 1
Number= 9
Number= 7
Number= 3
[1, 9, 7, 3]
avg=  5.0


Activity 7

In [ ]:
def largest(num, k):
    num.sort(reverse=True)
    return num[k - 1]
s=int(input('What is the size of list '))
d=[]
su=0
for i in range(s):
  num=int(input('Number= '))
  d.append(num)
largest(d,s)

What is the size of list 4
Number= 2
Number= 4
Number= 6
Number= 8


2

Activity 8

In [ ]:
def digits(n):
    if n < 10:
        return n
    else:
        return (n % 10) + digits(n // 10)
num=int(input('Number= '))
print("Sum= ", digits(num))

Number= 453
Sum=  12


Activity 9

In [ ]:
def power(base, exponent):
    if exponent == 0:
        return 1
    elif exponent == 1:
        return base
    else:
        return base * power(base, exponent - 1)
num1=int(input('Base= '))
num2=int(input('exponent= '))
print(f"{num1}^{num2} =", power(num1, num2))

Base= 2
exponent= 3
2^3 = 8


Activity 10

In [ ]:
def gcd(a, b):
    if b == 0:
        return a
    else:
        return gcd(b, a % b)
num1=int(input('num1= '))
num2=int(input('num2= '))
print(f"GCD of {num1} and {num2} is", gcd(num1, num2))

num1= 3
num2= 6
GCD of 3 and 6 is 3


Activity 11

In [ ]:
import numpy as np
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Activity 12

In [ ]:
a1= np.arange(1, 10).reshape(3, 3)
a1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Activity 13

In [ ]:
a2=np.eye(3)
a2

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Activity 14

In [ ]:
a3=np.random.randint(1,100,10)
print(a3)
print("mean :",a3.mean())
print("standard deviation :", a3.std())

[30 32 30 97  1 12 76  3 51 45]
mean : 37.7
standard deviation : 29.284979084848256


Activity 15

In [ ]:
a4=np.arange(10,21)
a4

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
a4[:5]

array([10, 11, 12, 13, 14])

Activity 16

In [ ]:
a5=np.arange(16).reshape(4,4)
a5

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
a5[1]

array([4, 5, 6, 7])

Activity 17

In [ ]:
arr1=np.arange(1,6)
arr1

array([1, 2, 3, 4, 5])

In [ ]:
arr2=np.arange(6,11)
arr2

array([ 6,  7,  8,  9, 10])

In [ ]:
arr=arr1+arr2
arr

array([ 7,  9, 11, 13, 15])

Activity 18

In [ ]:
ar=np.random.rand(10)
ar

array([0.60783081, 0.50557941, 0.76028171, 0.59305387, 0.42545892,
       0.12996171, 0.21712307, 0.77523423, 0.48788976, 0.52439427])

In [ ]:
ar[ar<0.5]=0
ar

array([0.60783081, 0.50557941, 0.76028171, 0.59305387, 0.        ,
       0.        , 0.        , 0.77523423, 0.        , 0.52439427])